cezanne23/deepthinking

README.md
README  내용 수정입니다.
- 팀명/팀장/팀원 업데이트했습니다.
=> [FEATURE]Update README

deep_thinking/deep_thinking.sln, deep_thinking/deep_thinking/deep_thinking.vcxproj, deep_thinking/deep_thinking/deep_thinking.vcxproj.filters, deep_thinking/deep_thinking/deep_thinking.vcxproj.user, deep_thinking/deep_thinking_test/deep_thinking_test.vcxproj, deep_thinking/deep_thinking_test/deep_thinking_test.vcxproj.user, deep_thinking/deep_thinking_test/packages.config, deep_thinking/deep_thinking_test/pch.cpp, deep_thinking/deep_thinking_test/pch.h, deep_thinking/deep_thinking_test/test.cpp, readme.hs-will-lee
VS project files
- VS version: VS2022
- deep_thinking: project 
- deep_thinking: gtest project
=> Merge VS project files

deep_thinking/deep_thinking/EmployeeManager.cpp, deep_thinking/deep_thinking/EmployeeManager.h, deep_thinking/deep_thinking_test/EmployeeManagerTest.cpp
file read/write 기능 추가
file read/write 기능 테스트 추가
=> [FEATURE] file read/write 기능 추가

deep_thinking/deep_thinking_test/TC_CommandParser.h
- EXE 환경으로 실행 가능하도록 cpp 파일로 include 수정함
- 줄바꿈 LF 포멧으로 변경
=> [HOTFIX] fix build error with gTest

deep_thinking/deep_thinking/SearchEngine.cpp, deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
- add serach command parser
- add search option classes: name, id, phonenumber, cl, certi
- add TC for search options
- remove dummy EmployeeInfo class
=> [FEATURE] SearchEngine add search option

deep_thinking/deep_thinking/Employee.h, deep_thinking/deep_thinking/SearchEngine.cpp, deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
- Seach fake Test: TC를 위한 dummy DB생성
- Search option TC: id, name, birth d m y, certi, cl, phoneNum m l
- Search option 구현:  id, name, birth d m y, certi, cl, phoneNum m l
- 사유: 다음과 같이 맨 앞에 0이 붙어 있는 사번에 대한 처리를 위함. 이 경우 string -> int 변경 시 0
ADD, , , ,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
ADD, , , ,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
ADD, , , ,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
=> [TC, FEATURE] Seach engine option TC and development

deep_thinking/deep_thinking/EmployeeInfo.h, deep_thinking/deep_thinking_test/EmployeeInfoTest.cpp
**EmployeeInfo** 
getName()
getFirstName() 추가
getLastName() 추가
getBirthDate  이름 변경
getBirthYear 추가
getBirthMonth 추가
getBirthDay 추가
=> [FEATURE]  EmployeeInfo name/birthday 세부 api  추가

deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
- map header가 없어 수정
- 증복 TC 존재로 하나 삭제
=> [HOTFIX] fix build error on testcase

deep_thinking/deep_thinking/SearchPolicy.h
EmployeeInfo 의 API 변경에 따른 build error 수정
getBirthDate
getBirthYear
getBirthMonth
getBirthDay
=> [HOTFIX] fix build error by changing API

deep_thinking/deep_thinking_test/SearchEngineTest.cpp
최대 데이터가 있는 경우와  return data에 최대 데이터를 모두 넣어서 return 하는 경우입니다. 
이 TC 는 개인 피시에서 약 25sec 소요되고 있습니다. 
- Max 100000 data test
- return 100000 data
=> [TC] SeachEngine performance test

deep_thinking/deep_thinking/EmployeeInfo.h, deep_thinking/deep_thinking_test/EmployeeInfoTest.cpp
EmployeeInfo phonenumber세부 api 추가
getPhoneNum
getPhoneMidNum
getPhoneLastNum
=> [FEATURE] EmployeeInfo phonenumber세부 api 추가

deep_thinking/deep_thinking_test/SearchEngineTest.cpp
=> [CLEAN] remove SearchEngine Fail TC

deep_thinking/deep_thinking_test/Commandtest.cpp, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
- searID argument 변경 사항 반영
- Search에서 NAME keyword는 없음 -> name으로 변경
=> [HOTFIX] build error on gTEST 수정내용

deep_thinking/deep_thinking/EmployeeInfo.h, deep_thinking/deep_thinking/EmployeeInfoManager.h, deep_thinking/deep_thinking_test/EmployeeInfoTest.cpp
- EmployeeInfo Manager에 Map들을 추가하였습니다.
- EmployeeInfo에 Opeartor <, > 를 추가하였습니다.
=> [FEATURE] EmployeeInfoManager 내 map update와 EmployeeInfo Operator 구현

deep_thinking/deep_thinking/SearchEngine.cpp, deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
입력 paramter 에 DB 없이 search 할 수 있는 interface 추가
=> [Feature] searchEngine interface 

deep_thinking/deep_thinking/SearchEngine.cpp, deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
- add singleton DB to SearchEngine
- sdd TC for dingleton DB
searchID input 에 input DB 없이 입력하는 경우 singlton DB 사용하여 검색
~~~
SearchEngine searchEngine;
res = searchEngine.searchID(parser.split("DEL, , , ,employeeNum,18115040", ','));
~~~
=> [FEATURE] SearchEngine use singleton DB

deep_thinking/deep_thinking/Sorting.h, deep_thinking/deep_thinking/deep_thinking.vcxproj, deep_thinking/deep_thinking/deep_thinking.vcxproj.filters, deep_thinking/deep_thinking_test/SortingTest.cpp, deep_thinking/deep_thinking_test/deep_thinking_test.vcxproj
- Interface Sorting class를 이용 PriorityQueue를 통해 EmployeeInfo 오름차순 동작 확인하였습니다.
-  getTopk()를 통해 Top5의 결과를 받을 수 있습니다.
=> [FEATURE] Sorting class 구현내용입니다.

deep_thinking/deep_thinking/Command.cpp, deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking/EmployeeDB.h, deep_thinking/deep_thinking_test/Commandtest.cpp
DEL command 동작 추가 ( search 모드만)
DEL command 테스트 추가  ( search 모드만)
=> [FEATURE] DEL command 동작 추가

deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
=> [HOTFIX] fix build error

deep_thinking/deep_thinking_test/SearchEngineTest.cpp
Fixture test 시 다른 테스트에서 사용했던 DB를 clear 해 준 후에 테스트한다.
다른 Test module 에서 사용한 경우 DB에 남아 있는 데이터의 영향을 받아 삭제합니다.
=> [TC] clear DB before test

deep_thinking/deep_thinking/EmployeeInfo.h, deep_thinking/deep_thinking_test/EmployeeInfoTest.cpp
Modify command 를 위해 EmployeeInfo 변수 수정 함수 
- TCs for EmployeeInfo set
- features for  EmployeeInfo set
- TC all passed
=> [FEATURE] EmployeeInfo set values

deep_thinking/deep_thinking/Command.h
Merge Conflict수정하다 실수로 삭제한 코드입니다.
=> [HOTFIX] Build Error 수정

deep_thinking/deep_thinking/Command.cpp, deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking_test/Commandtest.cpp
DEL 출력 recording 정렬 추가
- displayEmployeeInfo  최종 정렬된 5개만 가져오는 함수 추가
=> [FEATURE] DEL 출력 recording 정렬 추가

deep_thinking/deep_thinking/EmployeeInfoManager.cpp, deep_thinking/deep_thinking/deep_thinking.vcxproj.user
project setting debug mode과  main 추가
- deep_thinking\x64\Debug 에  input_20_20.txt copy 필요
=> [SETTING] project debug setting 과  main integration

deep_thinking/deep_thinking/Command.cpp, deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking_test/Commandtest.cpp
[FEATURE] TC and Feature for MOD command
- TC for  MOD w/o -p option
- MOD command feature
=>  [FEATURE] TC and Feature for MOD command

deep_thinking/deep_thinking/EmployeeInfo.h
EmployeeInfo 중복코드개선과 coding style 적용
=> [CLEAN]  EmployeeInfo 중복코드개선과 coding style 적용

deep_thinking/deep_thinking/Command.cpp
=> [BUGFix] fix modify command birth

deep_thinking/deep_thinking/ArgumentChecker.h, deep_thinking/deep_thinking/Command.cpp, deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking/CommandParser.cpp, deep_thinking/deep_thinking/CommandParser.h, deep_thinking/deep_thinking/Employee.h, deep_thinking/deep_thinking/EmployeeInfoManager.cpp, deep_thinking/deep_thinking/SearchEngine.cpp, deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking/Sorting.h, deep_thinking/deep_thinking/StringSplitter.h, deep_thinking/deep_thinking/deep_thinking.vcxproj, deep_thinking/deep_thinking/deep_thinking.vcxproj.filters, deep_thinking/deep_thinking/main.cpp, deep_thinking/deep_thinking_test/test.cpp
[CLEAN]  coding style 적용 및  api  사용 수정 ,  사용하지 않는 파일 삭제
=> [CLEAN]  coding style 적용 및  api  사용 수정

deep_thinking/deep_thinking_test/Commandtest.cpp
- add mod search option test
- add additional mod print option test
=> [TC] TC for MOD commands

deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking/Sorting.h, deep_thinking/deep_thinking_test/SortingTest.cpp
[Performance]  update sorting logic for -p option
- empolyeeInfo list 생성 로직 제거
- 출력 record 옵션 정렬을  vector<string> : employeeNum 기준으로 변경
=> [Performance] -p option을 위한 sorting type 변경

deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking/Sorting.h, deep_thinking/deep_thinking_test/SortingTest.cpp
- PQ 대신 algorithm partial_sort_copy API를 사용하였습니다.
=> [REFACTOR] partial_sort_copy 적용

deep_thinking/deep_thinking/Command.h
coding style 적용
unused instance 사용 제거
=> 함수 내부 local 변수 사용으로 변경함
=> [CLEAN] coding style 적용 및 unused instance 사용 제거

deep_thinking/deep_thinking/Command.cpp, deep_thinking/deep_thinking/Command.h, deep_thinking/deep_thinking/SearchEngine.cpp, deep_thinking/deep_thinking/SearchEngine.h, deep_thinking/deep_thinking/SearchPolicy.h, deep_thinking/deep_thinking/main.cpp, deep_thinking/deep_thinking_test/CommandParserTest.cpp, deep_thinking/deep_thinking_test/SearchEngineTest.cpp
- help message for no args params
=> [FETURE] add help message
